# Generated by Django 5.2.14 on 2026-05-15 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Food Image')),
                ('food_name', models.CharField(max_length=200, verbose_name='Detected Food Name')),
                ('food_category', models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('other', 'Other')], default='other', max_length=50, verbose_name='Food Category')),
                ('prediction', models.CharField(choices=[('Fresh', 'Fresh'), ('Semi-Fresh', 'Semi-Fresh'), ('Rotten', 'Rotten')], max_length=20, verbose_name='Freshness Prediction')),
                ('freshness_score', models.FloatField(default=0.0, verbose_name='Freshness Score (%)')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Confidence Score (%)')),
                ('shelf_life_days', models.IntegerField(default=0, verbose_name='Shelf Life Remaining (days)')),
                ('shelf_life_hours', models.IntegerField(default=0, verbose_name='Shelf Life Remaining (hours)')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Estimated Expiry Date')),
                ('storage_suggestion', models.TextField(blank=True, verbose_name='AI Storage Suggestion')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Scan Timestamp')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='User IP')),
            ],
            options={
                'verbose_name': 'Food Scan',
                'verbose_name_plural': 'Food Scans',
                'ordering': ['-timestamp'],
            },
        ),
    ]
